name: Scrape Bogor Air Quality Profile

on:
  schedule:
    - cron: '0 4,12,20 * * *'  # runs at 04:00, 12:00, 20:00 local time

permissions:
  contents: read

jobs:
  airquality-scrape:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['4.1.1']
    env:
      ATLAS_URL: ${{ secrets.ATLAS_URL }}
      ATLAS_COLLECTION: ${{ secrets.ATLAS_COLLECTION }}
      ATLAS_DB: ${{ secrets.ATLAS_DB }}
    steps:
      - name: Start time
        run: echo "$(date) ** $(TZ=Asia/Jakarta date)"
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install mongolite package
        run: Rscript -e 'install.packages("mongolite", dependencies = TRUE)'
      - name: Install rvest package
        run: Rscript -e 'install.packages("rvest", dependencies = TRUE)'  
      - name: Install dplyr package
        run: Rscript -e 'install.packages("dplyr", dependencies = TRUE)'  
      - name: Install lubridate package
        run: Rscript -e 'install.packages("lubridate", dependencies = TRUE)'  
      - name: Scrape data 
        run: Rscript scrape.R
